### ISSUE TITLE
Add muting when playerctl reports title "Spotify-"

### ISSUE THREAD

**Issue by Waaflee** [StarPlatin4m/spotblock-rs#3]
Some internal Spotify propaganda starts with "Spotify-" instead of "Advertisement-"
It would be good to add and OR conditional with those 2. 
I don't know rust otherwise I would do a Pull Request.

Example: 

`> playerctl --player=spotify metadata --format '{{ title }}-{{ artist }}'`
`> Spotify-`

**Comment by Waaflee** [comment]
Pull request to fix it on #4, was easier than expected

**Comment by imkival** [comment]
Thanks for your contribution!
It has been merged

Let me know if the issue still persists.
