### ISSUE TITLE
Spotblock-run starts Spotify muted and stays muted when I start or resume a song.

### ISSUE THREAD

**Issue by Ryuo1** [StarPlatin4m/spotblock-rs#8]
And when I unmute through here:
![image](https://user-images.githubusercontent.com/77712873/167805618-e6bd6a34-1628-4c71-a040-c092743cd0cc.png)
or
here: (by clicking the muted icon)
![image](https://user-images.githubusercontent.com/77712873/167805770-fae28930-fafd-4afb-9b14-868e21ef7280.png)
And when I unmute it,
Spotify plays music normally, but when an Advertisement comes up, it doesn't get muted.

This issue had started I think 4 days ago.
And yes, I did update spotblock-rs after #7 was merged, but the problem was still there.

**Comment by KivalM** [comment]
When you are unmuting it, was it initially muted due to the program, or did you mute it manually?

**Comment by Ryuo1** [comment]
> When you are unmuting it, was it initially muted due to the program, or did you mute it manually?

It was muted by the program.

**Comment by albarozzz** [comment]
Uhmmmm, what does spotblock-rs show when opening it in a terminal (with spotify running)?
One more thing, what is the output of `playerctl --player=spotify metadata --format '{{mpris:trackid}}'` and `pactl list sink-inputs` when an ad is being reproduced?

**Comment by KivalM** [comment]
> Uhmmmm, what does spotblock-rs show when opening it in a terminal (with spotify running)? One more thing, what is the output of `playerctl --player=spotify metadata --format '{{mpris:trackid}}'` and `pactl list sink-inputs` when an ad is being reproduced?

@Taughtimp2786 this.

The only cause I can think of at the moment is that ```playerctl --player=spotify metadata --format '{{mpris:trackid}}'``` is returning an empty string.

**Comment by Ryuo1** [comment]
I am not at home right now, so I can't test anything.

**Comment by Ryuo1** [comment]
Ok so I ran that playerctl command, and it turned out I didn't have playerctl installed. I don't how the ads were being muted before.
Anyways, after I installed playerctl, spotblock-rs started working normally.
