### ISSUE TITLE
Spotblock as a systemd service

### ISSUE THREAD

**Issue by R1D3R175** [StarPlatin4m/spotblock-rs#9]
It would be cool if Spotblock could be a service, sometimes I forget to run it whenever I boot my Linux and encounter the mood-breaking ad :oo

**Comment by KivalM** [comment]
It would make sense to do that for better compatibility with the Linux ecosystem. However, this is unnecessary. 

You can add `spotblock-rs&` to autostart via your distro autostart menu or your .bashrc or alternative.

**Comment by Ryuo1** [comment]
> It would make sense to do that for better compatibility with the Linux ecosystem. However, this is unnecessary.
> 
> You can add `spotblock-rs&` to autostart via your distro autostart menu or your .bashrc or alternative.

I am sorry for being stupid, but why the '&' after 'spotblock-rs'?

**Comment by baudneo** [comment]
The '&' puts spotblock-rs into the background, which allows the autostart to continue on with whatever else it is doing instead of running it in the foreground and possibly stalling the rest of the autostart process.
